### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by placeforyiming** [prs-eth/Dynamic-LiDAR-Resimulation#2]
Hi,

Thanks for the great work.

I'm interested in re-implementing your project, but got confused a little bit about the coding style of the open-sourced code. It would be great if you can help me check out ideas.

In your implementation, can I say only the training part follow the nerf-studio style? I mean, all other parts including the dataset preparation, the testing, and the visualization are all not using the nerf-studio style. Is this just because following the nerfstudio style is clumsy sometimes or is there any other critical reasons that may undermine the correctness of the implementation?

**Comment by hanfeng-wu** [comment]
Hi, Thank you for your interest in our work. Indeed only the training part "partially" follows the nerf-studio style, because our work is LiDAR based and the native nerf-studio framework is Camera based hence incompatible in lots of areas e.g. data manager, visualization. You can freely re-implement the code in other styles, I don't see any critical reason why nerf-studio has to be chosen, yet the training framework of nerf-studio is indeed very handy.
